name: Clean docker hub tags

on:
  delete

jobs:
  clean:
    runs-on: ubuntu-18.04
    name: Clean docker hub tags
    steps:
      - run: echo $GITHUB_SHA
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_EVENT_PATH
      - run: cat $GITHUB_EVENT_PATH
